---
- name: Create a key pair based on the personal I have
  amazon.aws.ec2_key:
    name: "{{ key }}"
    region: "{{ region }}"
    aws_access_key: "{{ acc_key }}"
    aws_secret_key: "{{ sec_key }}"
    key_material: "{{ lookup('file', '/home/lebreda/.ssh/id_rsa.pub') }}"
    tags:
      creation_type: Ansible
...
