---
- name: Create the "{{ secgroup }}" security group
  amazon.aws.ec2_group:
    name: "{{ secgroup }}"
    description: This group allows HTTP and HTTPS connection
    region: "{{ region }}"
    aws_access_key: "{{ acc_key }}"
    aws_secret_key: "{{ sec_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
...
